# Using Convolution Neural Network

In [1]:
import tensorflow as tf
from tensorflow.keras import layers,models
import os
import pandas as pd
import cv2

In [2]:
def makedf(img1,img2,path1,path2): 
    df=pd.DataFrame(columns=['images','outcome'])
    
    for image in img1:
        p=path1+'/'+image
        img=cv2.imread(p)
        df.loc[len(df.index)] = [img,'benign']
    
    for image in img2:
        p=path2+'/'+image
        img=cv2.imread(p)
        df.loc[len(df.index)] = [img,'malignant']
        
    
    return df

In [3]:
path1='C:/Users/ASUS/data/train/benign'
path2='C:/Users/ASUS/data/train/malignant'
images1=os.listdir(path1)
images2=os.listdir(path2)
df1=makedf(images1,images2,path1,path2)

In [4]:
df1.head

<bound method NDFrame.head of                                                  images    outcome
0     [[[193, 175, 222], [188, 177, 223], [190, 177,...     benign
1     [[[133, 120, 212], [132, 121, 213], [133, 122,...     benign
2     [[[140, 128, 210], [141, 131, 208], [147, 137,...     benign
3     [[[125, 118, 161], [123, 119, 161], [125, 118,...     benign
4     [[[180, 159, 234], [182, 162, 235], [179, 159,...     benign
...                                                 ...        ...
2632  [[[104, 106, 140], [102, 102, 142], [106, 105,...  malignant
2633  [[[28, 35, 50], [35, 42, 59], [40, 52, 70], [4...  malignant
2634  [[[154, 170, 213], [155, 170, 216], [156, 172,...  malignant
2635  [[[185, 182, 231], [186, 183, 232], [184, 184,...  malignant
2636  [[[86, 89, 127], [92, 94, 128], [98, 98, 128],...  malignant

[2637 rows x 2 columns]>

In [5]:
x=df1.iloc[:,0]

In [6]:
x.shape

(2637,)

In [7]:
x[0].shape

(224, 224, 3)

In [8]:
import numpy as np

In [9]:
y = df1['outcome'].map({"benign":0,"malignant":1})

In [10]:
y

0       0
1       0
2       0
3       0
4       0
       ..
2632    1
2633    1
2634    1
2635    1
2636    1
Name: outcome, Length: 2637, dtype: int64

In [11]:
y=np.asarray(y)

In [12]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [13]:
x.shape

(2637,)

In [14]:
y.shape

(2637,)

In [15]:
x=np.stack(x).astype(None)

In [16]:
x

array([[[[193., 175., 222.],
         [188., 177., 223.],
         [190., 177., 223.],
         ...,
         [155., 156., 212.],
         [152., 153., 209.],
         [150., 153., 208.]],

        [[196., 171., 221.],
         [196., 175., 220.],
         [192., 172., 219.],
         ...,
         [150., 153., 208.],
         [154., 155., 211.],
         [161., 155., 214.]],

        [[193., 174., 223.],
         [199., 177., 225.],
         [192., 174., 221.],
         ...,
         [155., 156., 212.],
         [158., 158., 212.],
         [155., 156., 212.]],

        ...,

        [[153., 152., 196.],
         [158., 155., 201.],
         [160., 152., 199.],
         ...,
         [140., 144., 195.],
         [146., 147., 198.],
         [153., 147., 200.]],

        [[152., 149., 198.],
         [154., 151., 200.],
         [157., 151., 198.],
         ...,
         [145., 142., 197.],
         [148., 149., 199.],
         [154., 148., 201.]],

        [[152., 149., 198.],
       

In [17]:
x.dtype

dtype('float64')

In [18]:
x=x/255.0

In [19]:
x

array([[[[0.75686275, 0.68627451, 0.87058824],
         [0.7372549 , 0.69411765, 0.8745098 ],
         [0.74509804, 0.69411765, 0.8745098 ],
         ...,
         [0.60784314, 0.61176471, 0.83137255],
         [0.59607843, 0.6       , 0.81960784],
         [0.58823529, 0.6       , 0.81568627]],

        [[0.76862745, 0.67058824, 0.86666667],
         [0.76862745, 0.68627451, 0.8627451 ],
         [0.75294118, 0.6745098 , 0.85882353],
         ...,
         [0.58823529, 0.6       , 0.81568627],
         [0.60392157, 0.60784314, 0.82745098],
         [0.63137255, 0.60784314, 0.83921569]],

        [[0.75686275, 0.68235294, 0.8745098 ],
         [0.78039216, 0.69411765, 0.88235294],
         [0.75294118, 0.68235294, 0.86666667],
         ...,
         [0.60784314, 0.61176471, 0.83137255],
         [0.61960784, 0.61960784, 0.83137255],
         [0.60784314, 0.61176471, 0.83137255]],

        ...,

        [[0.6       , 0.59607843, 0.76862745],
         [0.61960784, 0.60784314, 0.78823529]

In [20]:
x.shape

(2637, 224, 224, 3)

In [21]:
path3='C:/Users/ASUS/data/test/benign'
path4='C:/Users/ASUS/data/test/malignant'
images3=os.listdir(path3)
images4=os.listdir(path4)
df2=makedf(images3,images4,path3,path4)

In [22]:
x_test=df2.iloc[:,0]
y_test = df2['outcome'].map({"benign":0,"malignant":1})

In [23]:
x_test=np.stack(x_test).astype(None)

In [24]:
x_test

array([[[[148., 140., 177.],
         [156., 151., 190.],
         [154., 152., 188.],
         ...,
         [160., 156., 192.],
         [159., 156., 188.],
         [158., 153., 185.]],

        [[160., 156., 198.],
         [171., 168., 213.],
         [171., 169., 211.],
         ...,
         [178., 174., 215.],
         [177., 173., 214.],
         [171., 168., 213.]],

        [[158., 152., 193.],
         [168., 166., 208.],
         [170., 166., 207.],
         ...,
         [179., 175., 210.],
         [175., 170., 209.],
         [175., 166., 209.]],

        ...,

        [[160., 157., 189.],
         [171., 171., 207.],
         [171., 173., 207.],
         ...,
         [177., 177., 213.],
         [176., 175., 214.],
         [172., 171., 211.]],

        [[160., 158., 188.],
         [172., 169., 208.],
         [171., 171., 207.],
         ...,
         [175., 175., 215.],
         [172., 171., 211.],
         [171., 170., 210.]],

        [[160., 155., 187.],
       

In [25]:
x_test=x_test/255.0

In [26]:
y_test=np.asarray(y_test)

In [27]:
cnn=models.Sequential([
    #convolutional layer
    layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(224, 224, 3)),
    layers.MaxPooling2D((2, 2)),
    
    layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(2, activation='softmax')
])

In [28]:
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [29]:
cnn.fit(x, y, epochs=10)

Epoch 1/10
83/83 [==============================] - 142s 2s/step - loss: 0.8617 - accuracy: 0.6925
Epoch 2/10
83/83 [==============================] - 132s 2s/step - loss: 0.4883 - accuracy: 0.7550
Epoch 3/10
83/83 [==============================] - 157s 2s/step - loss: 0.4178 - accuracy: 0.7986
Epoch 4/10
83/83 [==============================] - 125s 2s/step - loss: 0.3762 - accuracy: 0.8108
Epoch 5/10
83/83 [==============================] - 106s 1s/step - loss: 0.3457 - accuracy: 0.8278
Epoch 6/10
83/83 [==============================] - 110s 1s/step - loss: 0.3407 - accuracy: 0.8453
Epoch 7/10
83/83 [==============================] - 117s 1s/step - loss: 0.3408 - accuracy: 0.8328
Epoch 8/10
83/83 [==============================] - 115s 1s/step - loss: 0.2898 - accuracy: 0.8650
Epoch 9/10
83/83 [==============================] - 116s 1s/step - loss: 0.2996 - accuracy: 0.8669
Epoch 10/10
83/83 [==============================] - 146s 2s/step - loss: 0.2445 - accuracy: 0.8881


In [30]:
cnn.evaluate(x_test,y_test)

21/21 [==============================] - 9s 384ms/step - loss: 0.4340 - accuracy: 0.8227


[0.4340308904647827, 0.8227272629737854]

Here CNN is giving 90% accuracy with train and 83% accuracy with train data which is greatest among all other ml algorithms
Thus, CNN is best for classifying images

In [31]:
y_pred = cnn.predict(x_test)

21/21 [==============================] - 8s 374ms/step


In [32]:
y_pred

array([[5.1286131e-01, 4.8713863e-01],
       [9.7546250e-01, 2.4537463e-02],
       [9.9999642e-01, 3.5640987e-06],
       ...,
       [4.1636309e-01, 5.8363694e-01],
       [5.0939471e-02, 9.4906050e-01],
       [4.3662408e-01, 5.6337595e-01]], dtype=float32)

In [33]:
y_classes = [np.argmax(element) for element in y_pred]

In [34]:
y_classes=np.asarray(y_classes)

In [35]:
y_classes


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [36]:
from sklearn import metrics

In [37]:
cm=metrics.confusion_matrix(y_test,y_classes)

In [38]:
cm

array([[323,  37],
       [ 80, 220]], dtype=int64)

In [39]:
metrics.f1_score(y_test,y_classes)

0.7899461400359066

In [40]:
metrics.precision_score(y_test,y_classes)

0.8560311284046692

In [41]:
metrics.recall_score(y_test,y_classes)

0.7333333333333333

In [42]:
metrics.accuracy_score(y_test,y_classes)

0.8227272727272728